-- Add token tracking and cost columns to usage metrics
-- Migration: Add input_tokens, output_tokens, and cost_cents columns

ALTER TABLE va_usage_metrics
ADD COLUMN IF NOT EXISTS input_tokens INTEGER,
ADD COLUMN IF NOT EXISTS output_tokens INTEGER,
ADD COLUMN IF NOT EXISTS cost_cents DECIMAL(10, 4);

-- Add index for efficient analytics queries
CREATE INDEX IF NOT EXISTS idx_usage_metrics_user_created
ON va_usage_metrics(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_usage_metrics_cost
ON va_usage_metrics(user_id, cost_cents)
WHERE cost_cents IS NOT NULL;

-- Add comments for documentation
COMMENT ON COLUMN va_usage_metrics.input_tokens IS 'Number of input tokens sent to the LLM';
COMMENT ON COLUMN va_usage_metrics.output_tokens IS 'Number of output tokens generated by the LLM';
COMMENT ON COLUMN va_usage_metrics.cost_cents IS 'Cost of this API call in cents (e.g., 0.05 = $0.0005)';
